### ISSUE TITLE
License

### ISSUE THREAD

**Issue by florian-obernberger** [McCrafterIV/etebase-dart#1]
I'd like use / contribute / fork your project, since I'd love to use etebase in a flutter app, but one thing that's unclear to me is what license you put this code under?

Could you maybe add a License to the repository?

Thank you so much in advance and best regards!

**Comment by McCrafterIV** [comment]
Thanks for the interest in my repo!

I would definitely be open to contributions since as of now, basically nothing works. Its more a simple adaption of the js library as a working package. The problems mostly focus around the crypto aspect, which I haven't gotten around to work on for a long while now.

I will add a license shortly.
